"""Typed access to the Rust AI Session Search service.

This module is available in wheels built with maturin. Keeping the extension in
``_native`` prevents binding details from becoming the public API namespace.
"""

from ._native import (
    AnalysisQuery,
    DateRangeQuery,
    FileQueryRequest,
    MessageQuery,
    MessageSearchTarget,
    MessageSelector,
    MessageSequenceRange,
    NativeChangedFileEvidence,
    NativeCorrectionMatch,
    NativeExportDocument,
    NativeFileCrossRef,
    NativeFileEditSummary,
    NativeFileVersion,
    NativeMessageHit,
    NativeMessagePreview,
    NativeMessageRef,
    NativePlanningCount,
    NativeProviderSourceStatus,
    NativeReconstructedFile,
    NativeRefEvidence,
    NativeRoleStatistic,
    NativeSessionInspection,
    NativeSessionRecord,
    NativeSessionSearchHit,
    NativeSessionTimeProfile,
    NativeToolActivity,
    QueryScope,
    RefreshOutcome,
    SessionQuery,
    SessionSearch,
)

__all__ = [
    "AnalysisQuery",
    "DateRangeQuery",
    "FileQueryRequest",
    "MessageQuery",
    "MessageSearchTarget",
    "MessageSelector",
    "MessageSequenceRange",
    "NativeChangedFileEvidence",
    "NativeCorrectionMatch",
    "NativeExportDocument",
    "NativeFileCrossRef",
    "NativeFileEditSummary",
    "NativeFileVersion",
    "NativeMessageHit",
    "NativeMessagePreview",
    "NativeMessageRef",
    "NativePlanningCount",
    "NativeProviderSourceStatus",
    "NativeReconstructedFile",
    "NativeRefEvidence",
    "NativeRoleStatistic",
    "NativeSessionInspection",
    "NativeSessionRecord",
    "NativeSessionSearchHit",
    "NativeSessionTimeProfile",
    "NativeToolActivity",
    "QueryScope",
    "RefreshOutcome",
    "SessionQuery",
    "SessionSearch",
]
